// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "NativeGameplayTags.h"

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Shadow_ShadowStep);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Shadow_VeilWall);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Cooldown_Shadow_ShadowStep);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Cooldown_Shadow_VeilWall);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Warden_ArcBarrier);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Warden_BurstLeap);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Cooldown_Warden_ArcBarrier);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Cooldown_Warden_BurstLeap);
